version: 2

models:

  - name: agg_orders
    description: This model aggregates order-level data

    columns:
      - name: order_date
        description: Date (UTC) of the order
        tests:
          - not_null
      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: total_order_cost
        description: Sum of all order cost
      - name: total_order_items_subtotal
        description: Sum of all order items subtotal
      - name: total_order_items_count
        description: Sum of all order items count
